sudo: required

services:
  - docker

before_install:
  - docker build -t madhu051196/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run madhu051196/react-test npm test -- --coverage

after_success:
  - docker build -t madhu051196/multi-client ./client
  - docker build -t madhu051196/multi-nginx ./nginx
  - docker build -t madhu051196/multi-server ./server
  - docker build -t madhu051196/multi-worker ./worker
  #Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push madhu051196/multi-client
  - docker push madhu051196/multi-nginx
  - docker push madhu051196/multi-server
  - docker push madhu051196/multi-worker
